# Generated by Django 2.2.13 on 2021-04-26 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('EDITOR', 'Editor')], default='ADMIN', max_length=10),
        ),
    ]
