# Generated by Django 2.2.13 on 2021-04-28 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210427_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.PositiveSmallIntegerField(choices=[(1, 'admin'), (2, 'editor'), (3, 'user'), (4, 'supervisor')], primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='roles',
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(to='account.Role'),
        ),
    ]
