# Generated by Django 3.0 on 2019-12-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0004_auto_20191209_1500'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-created',)},
        ),
        migrations.RenameField(
            model_name='project',
            old_name='created_time',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='update_time',
            new_name='updated',
        ),
        migrations.RemoveField(
            model_name='project',
            name='included_module',
        ),
        migrations.AddField(
            model_name='project',
            name='included_element',
            field=models.ManyToManyField(related_name='included_element', to='elements.Element'),
        ),
    ]
