# Generated by Django 2.0.13 on 2019-08-14 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_module_modules_name'),
        ('projects', '0002_project_included_module'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='included_module',
        ),
        migrations.AddField(
            model_name='project',
            name='included_module',
            field=models.ManyToManyField(related_name='included_module', to='modules.Module'),
        ),
    ]
