# Generated by Django 2.0.13 on 2019-08-27 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_included_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='included_material',
        ),
        migrations.AddField(
            model_name='project',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
