# Generated by Django 2.2.5 on 2019-09-10 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0001_initial'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=50)),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                (
                'included_material', models.ManyToManyField(related_name='included_material', to='materials.Material')),
                ('tag', models.ManyToManyField(related_name='included_tag_number', to='tags.Tag')),
            ],
        ),
    ]
