# Generated by Django 2.2.5 on 2019-09-09 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=50)),
                ('created_time', models.DateTimeField(auto_now=True)),
                (
                'included_material', models.ManyToManyField(related_name='included_material', to='materials.Material')),
            ],
        ),
    ]
