# Generated by Django 2.0.13 on 2019-08-13 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='included_material',
            field=models.ForeignKey(default='-1', on_delete=django.db.models.deletion.CASCADE, to='materials.Material'),
        ),
    ]
