# Generated by Django 3.0 on 2019-12-04 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0001_initial'),
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='element',
            field=models.ManyToManyField(to='elements.Element'),
        ),
        migrations.DeleteModel(
            name='Element',
        ),
    ]
