# Generated by Django 2.0.13 on 2019-08-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_module_included_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='module_name',
            field=models.CharField(default='-1', max_length=50),
        ),
    ]
