# Generated by Django 2.0.13 on 2019-08-14 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
        ('modules', '0003_module_modules_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='included_material',
        ),
        migrations.AddField(
            model_name='module',
            name='included_material',
            field=models.ManyToManyField(related_name='included_material', to='materials.Material'),
        ),
    ]
