# Generated by Django 2.0.13 on 2019-08-14 05:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0004_auto_20190814_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='created_time',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
