# Generated by Django 2.0.13 on 2019-08-16 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0005_module_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='module_name',
            field=models.CharField(max_length=50),
        ),
    ]
