# Generated by Django 2.2.5 on 2019-10-31 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('order_number', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=50)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand',
                                            to='brands.Brand')),
            ],
        ),
    ]
