# Generated by Django 3.2.3 on 2021-05-28 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='order_number',
            field=models.CharField(max_length=50),
        ),
    ]
