# Generated by Django 3.2.3 on 2021-05-28 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_alter_material_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='material_number',
            field=models.CharField(default='test', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
