# Generated by Django 3.0 on 2019-12-05 05:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('materials', '0002_auto_20191204_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='material',
            name='order_number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
