# Generated by Django 3.0 on 2019-12-09 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_auto_20191206_1024'),
        ('materials', '0003_auto_20191205_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='brands.Brand'),
        ),
    ]
