# Generated by Django 3.0 on 2019-12-24 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0003_auto_20191224_1753'),
        ('materials', '0005_auto_20191209_1320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ('brand', 'created')},
        ),
        migrations.RenameField(
            model_name='material',
            old_name='created_time',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='update_time',
            new_name='updated',
        ),
        migrations.AlterField(
            model_name='material',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='brands.Brand'),
        ),
    ]
