# Generated by Django 3.1.3 on 2020-11-18 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0001_initial'),
        ('tags', '0002_auto_20191206_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials.material')),
                ('element_tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tags.tag')),
            ],
        ),
    ]
