# Generated by Django 3.0 on 2019-12-04 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('tags', '0001_initial'),
        ('materials', '0002_auto_20191204_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_material',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.Material')),
                ('element_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tags.Tag')),
            ],
        ),
    ]
