# Generated by Django 3.0 on 2019-12-05 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_auto_20191204_1411'),
        ('tags', '0001_initial'),
        ('elements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='element_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials.Material'),
        ),
        migrations.AlterField(
            model_name='element',
            name='element_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tags.Tag'),
        ),
    ]
