# Generated by Django 2.2.13 on 2021-04-26 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elements', '0001_initial'),
        ('tags', '__first__'),
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='element_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials.Material'),
        ),
        migrations.AddField(
            model_name='element',
            name='element_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tags.Tag'),
        ),
    ]
