# Generated by Django 3.0 on 2019-12-09 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_auto_20191209_1320'),
        ('tags', '0002_auto_20191206_1024'),
        ('elements', '0003_auto_20191209_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='element_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials.Material'),
        ),
        migrations.AlterField(
            model_name='element',
            name='element_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tags.Tag'),
        ),
    ]
